plugin:
    name: 'uit.lighthouse::lang.plugin.name'
    description: 'uit.lighthouse::lang.plugin.description'
    author: Uit
    icon: oc-icon-share-alt
    homepage: ''
navigation:
    main-menu-item:
        label: 'uit.lighthouse::lang.navigation.schemes'
        url: uit/lighthouse/schemes
        icon: icon-share-alt
